### ISSUE TITLE
lag issue

### ISSUE THREAD

**Issue by blijgozertje** [NuVotifier/NuVotifier#134] opened 2019-05-07 19:49 UTC
timings: https://timings.aikar.co/?id=0f96e3b476b640a1ae6882f6adcb9214#timings
settings: https://gyazo.com/54c9b1ec16b3898ca2decb3b8421a264

TPS dropped to 16.2 but you can't see that in the timings.

**Comment by Ichbinjoe** [comment] 2019-05-07 19:56
Problems like this are always issues with plugins listening to the VoteEvent, causing the entire callstack to lag.

The timings you linked do not actually tell me where the issue lies. Please use https://www.spigotmc.org/resources/spark.57242/ and send me a report from that.

If I don't hear anything, I will close this in 24 hours as this is almost definitely not caused by NuVotifier.

**Comment by blijgozertje** [comment] 2019-05-07 20:00
Thanks for the fast response! Will get some results with that plugin asap.

**Comment by blijgozertje** [comment] 2019-05-07 20:11
https://sparkprofiler.github.io/#PHXa59LfTA

This is just one of a few minutes and not really a spike happened but we went to 19.2 TPS somewhere. Not sure if it is useful but will try to get some better ones right now.

**Comment by Ichbinjoe** [comment] 2019-05-07 20:36
So the only run time that Votifier is responsible for in that timing is caused by VoteRewards. However, at 0.24%, this is unlikely to be your problem.

**Comment by blijgozertje** [comment] 2019-05-08 18:02
Will do some research on how to use spark and find out what causes it.

Thanks for the fast support and you can close this whenever you want!

**Closed** 2019-05-08 18:16 UTC
