### ISSUE TITLE
Unexpected exception in the selector loop.

### ISSUE THREAD

**Issue by Royster-85** [NuVotifier/NuVotifier#250] opened 2021-06-01 17:31 UTC
### Information

**Platform on which you run NuVotifier**: Paper - Ver 753

**Version of NuVotifier**: 2.7.2

**Relevant log**: https://pastebin.com/6dNbmd7q

**Description**  
The following errors are occurring during a normal daily restart of the server. They also happen during stopping the server also. I am aware that a similar issue seems to have been noted, but this is still an issue that needs looking at.

**Steps to reproduce**  
Simply restarting or stopping the server causes this.

**Expected behaviour**  
Errors shouldn't be happening in the console during restart/stopping

**Comment by astei** [comment] 2021-06-01 17:48
Duplicate of #247 (which also explains why we can’t fix the issue).

**Closed by astei** 2021-06-01 17:48 UTC
Labels: bug
