### ISSUE TITLE
console bug

### ISSUE THREAD

**Issue by AdamDAuria** [NuVotifier/NuVotifier#266] opened 2021-07-14 07:46 UTC
### Information

**Platform on which you run NuVotifier**:  Paper

**Version of NuVotifier**: 

**Version: 2.7.3**

```
<!--
Getting this depends on your platform:

Bukkit: Use /version Votifier

Sponge: Use /sponge plugins and find NuVotifier

BungeeCord: No such command exists.

Velocity: Use /velocity plugins from in-game and hover over "nuvotifier"
-->
```

**Relevant log**: https://gist.github.com/AdamDAuria/1c6f23520ef30de94257bcb43c761b77
### Details

**Description**  
 at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428) ~[?:?]
    at com.vexsoftware.votifier.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
    at com.vexsoftware.votifier.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
    at com.vexsoftware.votifier.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
    at com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
at com.vexsoftware.votifier.io.netty.util.collection.IntObjectHashMap$2.iterator(IntObjectHashMap.java:224) ~[?:?]

**Steps to reproduce**  
a lot  of players online doing voting and such

**Expected behavior**  
not to have this error spam in console
```

```

**Comment by astei** [comment] 2021-08-03 06:08
Duplicate of #247

**Closed by astei** 2021-08-03 06:08 UTC
Labels: bug
