### ISSUE TITLE
Netty error on shutdown

### ISSUE THREAD

**Issue by Puremin0rez** [NuVotifier/NuVotifier#6] opened 2016-03-13 03:37 UTC
I very frequently receive this error on shutdown
http://pastebin.com/raw/A6jGjymW

**Comment by minecrafter** [comment] 2016-03-13 05:44
Possible upstream bug?

**Comment by EvilOlaf** [comment] 2016-05-20 09:48
Confirmed

```
[11:23:32] [nioEventLoopGroup-2-1/WARN]: Failed to fail the promise because it's done already: DefaultChannelPromise@3ede3239(success)
java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711) ~[?:1.8.0_91]
        at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
        at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.deregister(AbstractChannel.java:656) ~[nuvotifier-universal-2.3.2.2.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.fireChannelInactiveAndDeregister(AbstractChannel.java:626) ~[nuvotifier-universal-2.3.2.2.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:600) ~[nuvotifier-universal-2.3.2.2.jar:?]
        at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1107) ~[nuvotifier-universal-2.3.2.2.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:543) [nuvotifier-universal-2.3.2.2.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:32) [nuvotifier-universal-2.3.2.2.jar:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext$13.run(AbstractChannelHandlerContext.java:533) [nuvotifier-universal-2.3.2.2.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) [nuvotifier-universal-2.3.2.2.jar:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [nuvotifier-universal-2.3.2.2.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [nuvotifier-universal-2.3.2.2.jar:?]
        at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [nuvotifier-universal-2.3.2.2.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

2.3.2.2

**Comment by Ichbinjoe** [comment] 2016-08-15 23:49
Is this still an issue?

**Comment by minecrafter** [comment] 2017-01-15 23:49
Closing issue due to age.

**Closed by minecrafter** 2017-01-15 23:49 UTC
